name: Azure Automation Deployment
on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # principal json information in Action Secrets

    - name: Deploy Azure runbooks
      uses: azure/powershell@v1
      with:
        inlineScript: |
          pushd ./scripts/runbooks
          Import-AzAutomationRunbook -Path "test.ps1"  -Name test -Type PowerShell -AutomationAccountName 'workflow' -ResourceGroupName 'teste' -Force
          Publish-AzAutomationRunbook -Name test -AutomationAccountName 'workflow'  -ResourceGroupName 'teste'
          popd
        azPSVersion: "latest"

    # Logout
    - name: logout
      run: |
        az logout
    #run: |
        # $automationAccount = Get-AzAutomationAccount -ResourceGroupName "teste" -Name "workflow"
        #   runbook_name= "test.ps1"
        # # Import the runbook to Azure Automation
        #   $runbookContent = Get-Content -Path ./$runbook_name -Raw
        #   $runbookProperties = @{
        #       Name = $runbook_name
        #       Content = $runbookContent
        #       ResourceGroupName = "teste"
        #       AutomationAccountName = "workflow"
        #   }
        #   $importedRunbook = Import-AzAutomationRunbook @runbookProperties
        
        #   # Publish the runbook
        #   $publishProperties = @{
        #       ResourceGroupName = "teste"
        #       AutomationAccountName = "workflow"
        #       Name = $runbookName
        #   }
        #   Publish-AzAutomationRunbook @publishProperties
        
       
        # for file in ./*.py; do
        #   runbook_name=$(basename "$file" .py)
        #   az automation runbook create --resource-group "teste" --automation-account "workflow" --name "$runbook_name" --type Python3 
        # done

        # for file in ./*.ps1; do
        #   runbook_name=$(basename "$file" .ps1)
        #   az automation runbook create --resource-group "teste" --automation-account "workflow" --name "$runbook_name" --type PowerShell  
        # done
