name: Azure Automation Deployment
on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # principal json information in Action Secrets

    - name: Deploy to Azure Automation
      run: |
        for file in ./scripts/*; do
          runbook_name=$(basename "$file" .py)
          az automation runbook create --resource-group "teste" --automation-account "workflow" --name "$runbook_name" --type Python3 
          az automation runbook replace-content --automation-account-name "workflow" --resource-group "teste" --name "test" --content @/scripts/test.py
        done